// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Radarr.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Radarr.OpenApiClient.Feed.V3.Calendar.RadarrIcs
{
    /// <summary>
    /// Builds and executes requests for operations under \feed\v3\calendar\radarr.ics
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RadarrIcsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Radarr.OpenApiClient.Feed.V3.Calendar.RadarrIcs.RadarrIcsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RadarrIcsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/feed/v3/calendar/radarr.ics{?futureDays*,pastDays*,releaseTypes*,tags*,unmonitored*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Radarr.OpenApiClient.Feed.V3.Calendar.RadarrIcs.RadarrIcsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RadarrIcsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/feed/v3/calendar/radarr.ics{?futureDays*,pastDays*,releaseTypes*,tags*,unmonitored*}", rawUrl)
        {
        }
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Feed.V3.Calendar.RadarrIcs.RadarrIcsRequestBuilder.RadarrIcsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Feed.V3.Calendar.RadarrIcs.RadarrIcsRequestBuilder.RadarrIcsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Feed.V3.Calendar.RadarrIcs.RadarrIcsRequestBuilder.RadarrIcsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Feed.V3.Calendar.RadarrIcs.RadarrIcsRequestBuilder.RadarrIcsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Feed.V3.Calendar.RadarrIcs.RadarrIcsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Radarr.OpenApiClient.Feed.V3.Calendar.RadarrIcs.RadarrIcsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Radarr.OpenApiClient.Feed.V3.Calendar.RadarrIcs.RadarrIcsRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class RadarrIcsRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("futureDays")]
            public int? FutureDays { get; set; }
            [QueryParameter("pastDays")]
            public int? PastDays { get; set; }
            [Obsolete("This property is deprecated, use ReleaseTypesAsCalendarReleaseType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("releaseTypes")]
            public string[]? ReleaseTypes { get; set; }
#nullable restore
#else
            [QueryParameter("releaseTypes")]
            public string[] ReleaseTypes { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("releaseTypes")]
            public global::Soenneker.Radarr.OpenApiClient.Models.CalendarReleaseType[]? ReleaseTypesAsCalendarReleaseType { get; set; }
#nullable restore
#else
            [QueryParameter("releaseTypes")]
            public global::Soenneker.Radarr.OpenApiClient.Models.CalendarReleaseType[] ReleaseTypesAsCalendarReleaseType { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tags")]
            public string? Tags { get; set; }
#nullable restore
#else
            [QueryParameter("tags")]
            public string Tags { get; set; }
#endif
            [QueryParameter("unmonitored")]
            public bool? Unmonitored { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RadarrIcsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Feed.V3.Calendar.RadarrIcs.RadarrIcsRequestBuilder.RadarrIcsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
