// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AlternativeTitleResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The cleanTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CleanTitle { get; set; }
#nullable restore
#else
        public string CleanTitle { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The movieMetadataId property</summary>
        public int? MovieMetadataId { get; set; }
        /// <summary>The sourceType property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.SourceType? SourceType { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.AlternativeTitleResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.AlternativeTitleResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.AlternativeTitleResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cleanTitle", n => { CleanTitle = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "movieMetadataId", n => { MovieMetadataId = n.GetIntValue(); } },
                { "sourceType", n => { SourceType = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.SourceType>(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cleanTitle", CleanTitle);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("movieMetadataId", MovieMetadataId);
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.SourceType>("sourceType", SourceType);
            writer.WriteStringValue("title", Title);
        }
    }
}
#pragma warning restore CS0618
