// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CalendarReleaseType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "cinemaRelease")]
        #pragma warning disable CS1591
        CinemaRelease,
        #pragma warning restore CS1591
        [EnumMember(Value = "digitalRelease")]
        #pragma warning disable CS1591
        DigitalRelease,
        #pragma warning restore CS1591
        [EnumMember(Value = "physicalRelease")]
        #pragma warning disable CS1591
        PhysicalRelease,
        #pragma warning restore CS1591
    }
}
