// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CollectionUpdateResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The collectionIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? CollectionIds { get; set; }
#nullable restore
#else
        public List<int?> CollectionIds { get; set; }
#endif
        /// <summary>The minimumAvailability property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType? MinimumAvailability { get; set; }
        /// <summary>The monitored property</summary>
        public bool? Monitored { get; set; }
        /// <summary>The monitorMovies property</summary>
        public bool? MonitorMovies { get; set; }
        /// <summary>The qualityProfileId property</summary>
        public int? QualityProfileId { get; set; }
        /// <summary>The rootFolderPath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RootFolderPath { get; set; }
#nullable restore
#else
        public string RootFolderPath { get; set; }
#endif
        /// <summary>The searchOnAdd property</summary>
        public bool? SearchOnAdd { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.CollectionUpdateResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.CollectionUpdateResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.CollectionUpdateResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "collectionIds", n => { CollectionIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "minimumAvailability", n => { MinimumAvailability = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType>(); } },
                { "monitorMovies", n => { MonitorMovies = n.GetBoolValue(); } },
                { "monitored", n => { Monitored = n.GetBoolValue(); } },
                { "qualityProfileId", n => { QualityProfileId = n.GetIntValue(); } },
                { "rootFolderPath", n => { RootFolderPath = n.GetStringValue(); } },
                { "searchOnAdd", n => { SearchOnAdd = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<int?>("collectionIds", CollectionIds);
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType>("minimumAvailability", MinimumAvailability);
            writer.WriteBoolValue("monitored", Monitored);
            writer.WriteBoolValue("monitorMovies", MonitorMovies);
            writer.WriteIntValue("qualityProfileId", QualityProfileId);
            writer.WriteStringValue("rootFolderPath", RootFolderPath);
            writer.WriteBoolValue("searchOnAdd", SearchOnAdd);
        }
    }
}
#pragma warning restore CS0618
