// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CollectionMovieResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The cleanTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CleanTitle { get; set; }
#nullable restore
#else
        public string CleanTitle { get; set; }
#endif
        /// <summary>The folder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Folder { get; set; }
#nullable restore
#else
        public string Folder { get; set; }
#endif
        /// <summary>The genres property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Genres { get; set; }
#nullable restore
#else
        public List<string> Genres { get; set; }
#endif
        /// <summary>The images property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Radarr.OpenApiClient.Models.MediaCover>? Images { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Radarr.OpenApiClient.Models.MediaCover> Images { get; set; }
#endif
        /// <summary>The imdbId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImdbId { get; set; }
#nullable restore
#else
        public string ImdbId { get; set; }
#endif
        /// <summary>The isExcluded property</summary>
        public bool? IsExcluded { get; set; }
        /// <summary>The isExisting property</summary>
        public bool? IsExisting { get; set; }
        /// <summary>The overview property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Overview { get; set; }
#nullable restore
#else
        public string Overview { get; set; }
#endif
        /// <summary>The ratings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.Ratings? Ratings { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.Ratings Ratings { get; set; }
#endif
        /// <summary>The runtime property</summary>
        public int? Runtime { get; set; }
        /// <summary>The sortTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SortTitle { get; set; }
#nullable restore
#else
        public string SortTitle { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType? Status { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The tmdbId property</summary>
        public int? TmdbId { get; set; }
        /// <summary>The year property</summary>
        public int? Year { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.CollectionMovieResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.CollectionMovieResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.CollectionMovieResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cleanTitle", n => { CleanTitle = n.GetStringValue(); } },
                { "folder", n => { Folder = n.GetStringValue(); } },
                { "genres", n => { Genres = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "images", n => { Images = n.GetCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.MediaCover>(global::Soenneker.Radarr.OpenApiClient.Models.MediaCover.CreateFromDiscriminatorValue)?.AsList(); } },
                { "imdbId", n => { ImdbId = n.GetStringValue(); } },
                { "isExcluded", n => { IsExcluded = n.GetBoolValue(); } },
                { "isExisting", n => { IsExisting = n.GetBoolValue(); } },
                { "overview", n => { Overview = n.GetStringValue(); } },
                { "ratings", n => { Ratings = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.Ratings>(global::Soenneker.Radarr.OpenApiClient.Models.Ratings.CreateFromDiscriminatorValue); } },
                { "runtime", n => { Runtime = n.GetIntValue(); } },
                { "sortTitle", n => { SortTitle = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType>(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "tmdbId", n => { TmdbId = n.GetIntValue(); } },
                { "year", n => { Year = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cleanTitle", CleanTitle);
            writer.WriteStringValue("folder", Folder);
            writer.WriteCollectionOfPrimitiveValues<string>("genres", Genres);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.MediaCover>("images", Images);
            writer.WriteStringValue("imdbId", ImdbId);
            writer.WriteBoolValue("isExcluded", IsExcluded);
            writer.WriteBoolValue("isExisting", IsExisting);
            writer.WriteStringValue("overview", Overview);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.Ratings>("ratings", Ratings);
            writer.WriteIntValue("runtime", Runtime);
            writer.WriteStringValue("sortTitle", SortTitle);
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType>("status", Status);
            writer.WriteStringValue("title", Title);
            writer.WriteIntValue("tmdbId", TmdbId);
            writer.WriteIntValue("year", Year);
        }
    }
}
#pragma warning restore CS0618
