// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ColonReplacementFormat
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "delete")]
        #pragma warning disable CS1591
        Delete,
        #pragma warning restore CS1591
        [EnumMember(Value = "dash")]
        #pragma warning disable CS1591
        Dash,
        #pragma warning restore CS1591
        [EnumMember(Value = "spaceDash")]
        #pragma warning disable CS1591
        SpaceDash,
        #pragma warning restore CS1591
        [EnumMember(Value = "spaceDashSpace")]
        #pragma warning disable CS1591
        SpaceDashSpace,
        #pragma warning restore CS1591
        [EnumMember(Value = "smart")]
        #pragma warning disable CS1591
        Smart,
        #pragma warning restore CS1591
    }
}
