// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreditResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The character property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Character { get; set; }
#nullable restore
#else
        public string Character { get; set; }
#endif
        /// <summary>The creditTmdbId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreditTmdbId { get; set; }
#nullable restore
#else
        public string CreditTmdbId { get; set; }
#endif
        /// <summary>The department property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Department { get; set; }
#nullable restore
#else
        public string Department { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The images property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Radarr.OpenApiClient.Models.MediaCover>? Images { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Radarr.OpenApiClient.Models.MediaCover> Images { get; set; }
#endif
        /// <summary>The job property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Job { get; set; }
#nullable restore
#else
        public string Job { get; set; }
#endif
        /// <summary>The movieMetadataId property</summary>
        public int? MovieMetadataId { get; set; }
        /// <summary>The order property</summary>
        public int? Order { get; set; }
        /// <summary>The personName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PersonName { get; set; }
#nullable restore
#else
        public string PersonName { get; set; }
#endif
        /// <summary>The personTmdbId property</summary>
        public int? PersonTmdbId { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.CreditType? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.CreditResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.CreditResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.CreditResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "character", n => { Character = n.GetStringValue(); } },
                { "creditTmdbId", n => { CreditTmdbId = n.GetStringValue(); } },
                { "department", n => { Department = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "images", n => { Images = n.GetCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.MediaCover>(global::Soenneker.Radarr.OpenApiClient.Models.MediaCover.CreateFromDiscriminatorValue)?.AsList(); } },
                { "job", n => { Job = n.GetStringValue(); } },
                { "movieMetadataId", n => { MovieMetadataId = n.GetIntValue(); } },
                { "order", n => { Order = n.GetIntValue(); } },
                { "personName", n => { PersonName = n.GetStringValue(); } },
                { "personTmdbId", n => { PersonTmdbId = n.GetIntValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.CreditType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("character", Character);
            writer.WriteStringValue("creditTmdbId", CreditTmdbId);
            writer.WriteStringValue("department", Department);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.MediaCover>("images", Images);
            writer.WriteStringValue("job", Job);
            writer.WriteIntValue("movieMetadataId", MovieMetadataId);
            writer.WriteIntValue("order", Order);
            writer.WriteStringValue("personName", PersonName);
            writer.WriteIntValue("personTmdbId", PersonTmdbId);
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.CreditType>("type", Type);
        }
    }
}
#pragma warning restore CS0618
