// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreditType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "cast")]
        #pragma warning disable CS1591
        Cast,
        #pragma warning restore CS1591
        [EnumMember(Value = "crew")]
        #pragma warning disable CS1591
        Crew,
        #pragma warning restore CS1591
    }
}
