// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ExtraFileType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "subtitle")]
        #pragma warning disable CS1591
        Subtitle,
        #pragma warning restore CS1591
        [EnumMember(Value = "metadata")]
        #pragma warning disable CS1591
        Metadata,
        #pragma warning restore CS1591
        [EnumMember(Value = "other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
    }
}
