// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FileDateType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "cinemas")]
        #pragma warning disable CS1591
        Cinemas,
        #pragma warning restore CS1591
        [EnumMember(Value = "release")]
        #pragma warning disable CS1591
        Release,
        #pragma warning restore CS1591
    }
}
