// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ImportListResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The configContract property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConfigContract { get; set; }
#nullable restore
#else
        public string ConfigContract { get; set; }
#endif
        /// <summary>The enableAuto property</summary>
        public bool? EnableAuto { get; set; }
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>The fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Radarr.OpenApiClient.Models.Field>? Fields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Radarr.OpenApiClient.Models.Field> Fields { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The implementation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Implementation { get; set; }
#nullable restore
#else
        public string Implementation { get; set; }
#endif
        /// <summary>The implementationName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImplementationName { get; set; }
#nullable restore
#else
        public string ImplementationName { get; set; }
#endif
        /// <summary>The infoLink property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InfoLink { get; set; }
#nullable restore
#else
        public string InfoLink { get; set; }
#endif
        /// <summary>The listOrder property</summary>
        public int? ListOrder { get; set; }
        /// <summary>The listType property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.ImportListType? ListType { get; set; }
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.ProviderMessage? Message { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.ProviderMessage Message { get; set; }
#endif
        /// <summary>The minimumAvailability property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType? MinimumAvailability { get; set; }
        /// <summary>The minRefreshInterval property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MinRefreshInterval { get; set; }
#nullable restore
#else
        public string MinRefreshInterval { get; set; }
#endif
        /// <summary>The monitor property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.MonitorTypes? Monitor { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The presets property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Radarr.OpenApiClient.Models.ImportListResource>? Presets { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Radarr.OpenApiClient.Models.ImportListResource> Presets { get; set; }
#endif
        /// <summary>The qualityProfileId property</summary>
        public int? QualityProfileId { get; set; }
        /// <summary>The rootFolderPath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RootFolderPath { get; set; }
#nullable restore
#else
        public string RootFolderPath { get; set; }
#endif
        /// <summary>The searchOnAdd property</summary>
        public bool? SearchOnAdd { get; set; }
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Tags { get; set; }
#nullable restore
#else
        public List<int?> Tags { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.ImportListResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.ImportListResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.ImportListResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "configContract", n => { ConfigContract = n.GetStringValue(); } },
                { "enableAuto", n => { EnableAuto = n.GetBoolValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "fields", n => { Fields = n.GetCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.Field>(global::Soenneker.Radarr.OpenApiClient.Models.Field.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "implementation", n => { Implementation = n.GetStringValue(); } },
                { "implementationName", n => { ImplementationName = n.GetStringValue(); } },
                { "infoLink", n => { InfoLink = n.GetStringValue(); } },
                { "listOrder", n => { ListOrder = n.GetIntValue(); } },
                { "listType", n => { ListType = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.ImportListType>(); } },
                { "message", n => { Message = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.ProviderMessage>(global::Soenneker.Radarr.OpenApiClient.Models.ProviderMessage.CreateFromDiscriminatorValue); } },
                { "minRefreshInterval", n => { MinRefreshInterval = n.GetStringValue(); } },
                { "minimumAvailability", n => { MinimumAvailability = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType>(); } },
                { "monitor", n => { Monitor = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.MonitorTypes>(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "presets", n => { Presets = n.GetCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.ImportListResource>(global::Soenneker.Radarr.OpenApiClient.Models.ImportListResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "qualityProfileId", n => { QualityProfileId = n.GetIntValue(); } },
                { "rootFolderPath", n => { RootFolderPath = n.GetStringValue(); } },
                { "searchOnAdd", n => { SearchOnAdd = n.GetBoolValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("configContract", ConfigContract);
            writer.WriteBoolValue("enableAuto", EnableAuto);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.Field>("fields", Fields);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("implementation", Implementation);
            writer.WriteStringValue("implementationName", ImplementationName);
            writer.WriteStringValue("infoLink", InfoLink);
            writer.WriteIntValue("listOrder", ListOrder);
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.ImportListType>("listType", ListType);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.ProviderMessage>("message", Message);
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType>("minimumAvailability", MinimumAvailability);
            writer.WriteStringValue("minRefreshInterval", MinRefreshInterval);
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.MonitorTypes>("monitor", Monitor);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.ImportListResource>("presets", Presets);
            writer.WriteIntValue("qualityProfileId", QualityProfileId);
            writer.WriteStringValue("rootFolderPath", RootFolderPath);
            writer.WriteBoolValue("searchOnAdd", SearchOnAdd);
            writer.WriteCollectionOfPrimitiveValues<int?>("tags", Tags);
        }
    }
}
#pragma warning restore CS0618
