// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ImportListExclusionResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The configContract property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConfigContract { get; set; }
#nullable restore
#else
        public string ConfigContract { get; set; }
#endif
        /// <summary>The fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Radarr.OpenApiClient.Models.Field>? Fields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Radarr.OpenApiClient.Models.Field> Fields { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The implementation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Implementation { get; set; }
#nullable restore
#else
        public string Implementation { get; set; }
#endif
        /// <summary>The implementationName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImplementationName { get; set; }
#nullable restore
#else
        public string ImplementationName { get; set; }
#endif
        /// <summary>The infoLink property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InfoLink { get; set; }
#nullable restore
#else
        public string InfoLink { get; set; }
#endif
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.ProviderMessage? Message { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.ProviderMessage Message { get; set; }
#endif
        /// <summary>The movieTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MovieTitle { get; set; }
#nullable restore
#else
        public string MovieTitle { get; set; }
#endif
        /// <summary>The movieYear property</summary>
        public int? MovieYear { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The presets property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Radarr.OpenApiClient.Models.ImportListExclusionResource>? Presets { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Radarr.OpenApiClient.Models.ImportListExclusionResource> Presets { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Tags { get; set; }
#nullable restore
#else
        public List<int?> Tags { get; set; }
#endif
        /// <summary>The tmdbId property</summary>
        public int? TmdbId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.ImportListExclusionResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.ImportListExclusionResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.ImportListExclusionResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "configContract", n => { ConfigContract = n.GetStringValue(); } },
                { "fields", n => { Fields = n.GetCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.Field>(global::Soenneker.Radarr.OpenApiClient.Models.Field.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "implementation", n => { Implementation = n.GetStringValue(); } },
                { "implementationName", n => { ImplementationName = n.GetStringValue(); } },
                { "infoLink", n => { InfoLink = n.GetStringValue(); } },
                { "message", n => { Message = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.ProviderMessage>(global::Soenneker.Radarr.OpenApiClient.Models.ProviderMessage.CreateFromDiscriminatorValue); } },
                { "movieTitle", n => { MovieTitle = n.GetStringValue(); } },
                { "movieYear", n => { MovieYear = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "presets", n => { Presets = n.GetCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.ImportListExclusionResource>(global::Soenneker.Radarr.OpenApiClient.Models.ImportListExclusionResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "tmdbId", n => { TmdbId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("configContract", ConfigContract);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.Field>("fields", Fields);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("implementation", Implementation);
            writer.WriteStringValue("implementationName", ImplementationName);
            writer.WriteStringValue("infoLink", InfoLink);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.ProviderMessage>("message", Message);
            writer.WriteStringValue("movieTitle", MovieTitle);
            writer.WriteIntValue("movieYear", MovieYear);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.ImportListExclusionResource>("presets", Presets);
            writer.WriteCollectionOfPrimitiveValues<int?>("tags", Tags);
            writer.WriteIntValue("tmdbId", TmdbId);
        }
    }
}
#pragma warning restore CS0618
