// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class IndexerConfigResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The allowHardcodedSubs property</summary>
        public bool? AllowHardcodedSubs { get; set; }
        /// <summary>The availabilityDelay property</summary>
        public int? AvailabilityDelay { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The maximumSize property</summary>
        public int? MaximumSize { get; set; }
        /// <summary>The minimumAge property</summary>
        public int? MinimumAge { get; set; }
        /// <summary>The preferIndexerFlags property</summary>
        public bool? PreferIndexerFlags { get; set; }
        /// <summary>The retention property</summary>
        public int? Retention { get; set; }
        /// <summary>The rssSyncInterval property</summary>
        public int? RssSyncInterval { get; set; }
        /// <summary>The whitelistedHardcodedSubs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WhitelistedHardcodedSubs { get; set; }
#nullable restore
#else
        public string WhitelistedHardcodedSubs { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.IndexerConfigResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.IndexerConfigResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.IndexerConfigResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowHardcodedSubs", n => { AllowHardcodedSubs = n.GetBoolValue(); } },
                { "availabilityDelay", n => { AvailabilityDelay = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "maximumSize", n => { MaximumSize = n.GetIntValue(); } },
                { "minimumAge", n => { MinimumAge = n.GetIntValue(); } },
                { "preferIndexerFlags", n => { PreferIndexerFlags = n.GetBoolValue(); } },
                { "retention", n => { Retention = n.GetIntValue(); } },
                { "rssSyncInterval", n => { RssSyncInterval = n.GetIntValue(); } },
                { "whitelistedHardcodedSubs", n => { WhitelistedHardcodedSubs = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allowHardcodedSubs", AllowHardcodedSubs);
            writer.WriteIntValue("availabilityDelay", AvailabilityDelay);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("maximumSize", MaximumSize);
            writer.WriteIntValue("minimumAge", MinimumAge);
            writer.WriteBoolValue("preferIndexerFlags", PreferIndexerFlags);
            writer.WriteIntValue("retention", Retention);
            writer.WriteIntValue("rssSyncInterval", RssSyncInterval);
            writer.WriteStringValue("whitelistedHardcodedSubs", WhitelistedHardcodedSubs);
        }
    }
}
#pragma warning restore CS0618
