// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MetadataConfigResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The certificationCountry property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.TMDbCountryCode? CertificationCountry { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.MetadataConfigResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.MetadataConfigResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.MetadataConfigResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "certificationCountry", n => { CertificationCountry = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.TMDbCountryCode>(); } },
                { "id", n => { Id = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.TMDbCountryCode>("certificationCountry", CertificationCountry);
            writer.WriteIntValue("id", Id);
        }
    }
}
#pragma warning restore CS0618
