// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Modifier
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "regional")]
        #pragma warning disable CS1591
        Regional,
        #pragma warning restore CS1591
        [EnumMember(Value = "screener")]
        #pragma warning disable CS1591
        Screener,
        #pragma warning restore CS1591
        [EnumMember(Value = "rawhd")]
        #pragma warning disable CS1591
        Rawhd,
        #pragma warning restore CS1591
        [EnumMember(Value = "brdisk")]
        #pragma warning disable CS1591
        Brdisk,
        #pragma warning restore CS1591
        [EnumMember(Value = "remux")]
        #pragma warning disable CS1591
        Remux,
        #pragma warning restore CS1591
    }
}
