// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MonitorTypes
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "movieOnly")]
        #pragma warning disable CS1591
        MovieOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "movieAndCollection")]
        #pragma warning disable CS1591
        MovieAndCollection,
        #pragma warning restore CS1591
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
    }
}
