// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MovieEditorResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The addImportExclusion property</summary>
        public bool? AddImportExclusion { get; set; }
        /// <summary>The applyTags property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.ApplyTags? ApplyTags { get; set; }
        /// <summary>The deleteFiles property</summary>
        public bool? DeleteFiles { get; set; }
        /// <summary>The minimumAvailability property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType? MinimumAvailability { get; set; }
        /// <summary>The monitored property</summary>
        public bool? Monitored { get; set; }
        /// <summary>The moveFiles property</summary>
        public bool? MoveFiles { get; set; }
        /// <summary>The movieIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? MovieIds { get; set; }
#nullable restore
#else
        public List<int?> MovieIds { get; set; }
#endif
        /// <summary>The qualityProfileId property</summary>
        public int? QualityProfileId { get; set; }
        /// <summary>The rootFolderPath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RootFolderPath { get; set; }
#nullable restore
#else
        public string RootFolderPath { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Tags { get; set; }
#nullable restore
#else
        public List<int?> Tags { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.MovieEditorResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.MovieEditorResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.MovieEditorResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "addImportExclusion", n => { AddImportExclusion = n.GetBoolValue(); } },
                { "applyTags", n => { ApplyTags = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.ApplyTags>(); } },
                { "deleteFiles", n => { DeleteFiles = n.GetBoolValue(); } },
                { "minimumAvailability", n => { MinimumAvailability = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType>(); } },
                { "monitored", n => { Monitored = n.GetBoolValue(); } },
                { "moveFiles", n => { MoveFiles = n.GetBoolValue(); } },
                { "movieIds", n => { MovieIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "qualityProfileId", n => { QualityProfileId = n.GetIntValue(); } },
                { "rootFolderPath", n => { RootFolderPath = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("addImportExclusion", AddImportExclusion);
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.ApplyTags>("applyTags", ApplyTags);
            writer.WriteBoolValue("deleteFiles", DeleteFiles);
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType>("minimumAvailability", MinimumAvailability);
            writer.WriteBoolValue("monitored", Monitored);
            writer.WriteBoolValue("moveFiles", MoveFiles);
            writer.WriteCollectionOfPrimitiveValues<int?>("movieIds", MovieIds);
            writer.WriteIntValue("qualityProfileId", QualityProfileId);
            writer.WriteStringValue("rootFolderPath", RootFolderPath);
            writer.WriteCollectionOfPrimitiveValues<int?>("tags", Tags);
        }
    }
}
#pragma warning restore CS0618
