// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MovieStatusType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "tba")]
        #pragma warning disable CS1591
        Tba,
        #pragma warning restore CS1591
        [EnumMember(Value = "announced")]
        #pragma warning disable CS1591
        Announced,
        #pragma warning restore CS1591
        [EnumMember(Value = "inCinemas")]
        #pragma warning disable CS1591
        InCinemas,
        #pragma warning restore CS1591
        [EnumMember(Value = "released")]
        #pragma warning disable CS1591
        Released,
        #pragma warning restore CS1591
        [EnumMember(Value = "deleted")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
    }
}
