// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MovieResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The added property</summary>
        public DateTimeOffset? Added { get; set; }
        /// <summary>The addOptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.AddMovieOptions? AddOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.AddMovieOptions AddOptions { get; set; }
#endif
        /// <summary>The alternateTitles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Radarr.OpenApiClient.Models.AlternativeTitleResource>? AlternateTitles { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Radarr.OpenApiClient.Models.AlternativeTitleResource> AlternateTitles { get; set; }
#endif
        /// <summary>The certification property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Certification { get; set; }
#nullable restore
#else
        public string Certification { get; set; }
#endif
        /// <summary>The cleanTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CleanTitle { get; set; }
#nullable restore
#else
        public string CleanTitle { get; set; }
#endif
        /// <summary>The collection property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.MovieCollectionResource? Collection { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.MovieCollectionResource Collection { get; set; }
#endif
        /// <summary>The digitalRelease property</summary>
        public DateTimeOffset? DigitalRelease { get; set; }
        /// <summary>The folder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Folder { get; set; }
#nullable restore
#else
        public string Folder { get; set; }
#endif
        /// <summary>The folderName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FolderName { get; set; }
#nullable restore
#else
        public string FolderName { get; set; }
#endif
        /// <summary>The genres property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Genres { get; set; }
#nullable restore
#else
        public List<string> Genres { get; set; }
#endif
        /// <summary>The hasFile property</summary>
        public bool? HasFile { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The images property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Radarr.OpenApiClient.Models.MediaCover>? Images { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Radarr.OpenApiClient.Models.MediaCover> Images { get; set; }
#endif
        /// <summary>The imdbId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImdbId { get; set; }
#nullable restore
#else
        public string ImdbId { get; set; }
#endif
        /// <summary>The inCinemas property</summary>
        public DateTimeOffset? InCinemas { get; set; }
        /// <summary>The isAvailable property</summary>
        public bool? IsAvailable { get; set; }
        /// <summary>The keywords property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Keywords { get; set; }
#nullable restore
#else
        public List<string> Keywords { get; set; }
#endif
        /// <summary>The lastSearchTime property</summary>
        public DateTimeOffset? LastSearchTime { get; set; }
        /// <summary>The minimumAvailability property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType? MinimumAvailability { get; set; }
        /// <summary>The monitored property</summary>
        public bool? Monitored { get; set; }
        /// <summary>The movieFile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.MovieFileResource? MovieFile { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.MovieFileResource MovieFile { get; set; }
#endif
        /// <summary>The movieFileId property</summary>
        public int? MovieFileId { get; set; }
        /// <summary>The originalLanguage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.Language? OriginalLanguage { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.Language OriginalLanguage { get; set; }
#endif
        /// <summary>The originalTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalTitle { get; set; }
#nullable restore
#else
        public string OriginalTitle { get; set; }
#endif
        /// <summary>The overview property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Overview { get; set; }
#nullable restore
#else
        public string Overview { get; set; }
#endif
        /// <summary>The path property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The physicalRelease property</summary>
        public DateTimeOffset? PhysicalRelease { get; set; }
        /// <summary>The physicalReleaseNote property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhysicalReleaseNote { get; set; }
#nullable restore
#else
        public string PhysicalReleaseNote { get; set; }
#endif
        /// <summary>The popularity property</summary>
        public float? Popularity { get; set; }
        /// <summary>The qualityProfileId property</summary>
        public int? QualityProfileId { get; set; }
        /// <summary>The ratings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.Ratings? Ratings { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.Ratings Ratings { get; set; }
#endif
        /// <summary>The releaseDate property</summary>
        public DateTimeOffset? ReleaseDate { get; set; }
        /// <summary>The remotePoster property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RemotePoster { get; set; }
#nullable restore
#else
        public string RemotePoster { get; set; }
#endif
        /// <summary>The rootFolderPath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RootFolderPath { get; set; }
#nullable restore
#else
        public string RootFolderPath { get; set; }
#endif
        /// <summary>The runtime property</summary>
        public int? Runtime { get; set; }
        /// <summary>The secondaryYear property</summary>
        public int? SecondaryYear { get; set; }
        /// <summary>The secondaryYearSourceId property</summary>
        public int? SecondaryYearSourceId { get; set; }
        /// <summary>The sizeOnDisk property</summary>
        public long? SizeOnDisk { get; set; }
        /// <summary>The sortTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SortTitle { get; set; }
#nullable restore
#else
        public string SortTitle { get; set; }
#endif
        /// <summary>The statistics property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.MovieStatisticsResource? Statistics { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.MovieStatisticsResource Statistics { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType? Status { get; set; }
        /// <summary>The studio property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Studio { get; set; }
#nullable restore
#else
        public string Studio { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Tags { get; set; }
#nullable restore
#else
        public List<int?> Tags { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The titleSlug property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TitleSlug { get; set; }
#nullable restore
#else
        public string TitleSlug { get; set; }
#endif
        /// <summary>The tmdbId property</summary>
        public int? TmdbId { get; set; }
        /// <summary>The website property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Website { get; set; }
#nullable restore
#else
        public string Website { get; set; }
#endif
        /// <summary>The year property</summary>
        public int? Year { get; set; }
        /// <summary>The youTubeTrailerId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? YouTubeTrailerId { get; set; }
#nullable restore
#else
        public string YouTubeTrailerId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.MovieResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.MovieResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.MovieResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "addOptions", n => { AddOptions = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.AddMovieOptions>(global::Soenneker.Radarr.OpenApiClient.Models.AddMovieOptions.CreateFromDiscriminatorValue); } },
                { "added", n => { Added = n.GetDateTimeOffsetValue(); } },
                { "alternateTitles", n => { AlternateTitles = n.GetCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.AlternativeTitleResource>(global::Soenneker.Radarr.OpenApiClient.Models.AlternativeTitleResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "certification", n => { Certification = n.GetStringValue(); } },
                { "cleanTitle", n => { CleanTitle = n.GetStringValue(); } },
                { "collection", n => { Collection = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieCollectionResource>(global::Soenneker.Radarr.OpenApiClient.Models.MovieCollectionResource.CreateFromDiscriminatorValue); } },
                { "digitalRelease", n => { DigitalRelease = n.GetDateTimeOffsetValue(); } },
                { "folder", n => { Folder = n.GetStringValue(); } },
                { "folderName", n => { FolderName = n.GetStringValue(); } },
                { "genres", n => { Genres = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "hasFile", n => { HasFile = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "images", n => { Images = n.GetCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.MediaCover>(global::Soenneker.Radarr.OpenApiClient.Models.MediaCover.CreateFromDiscriminatorValue)?.AsList(); } },
                { "imdbId", n => { ImdbId = n.GetStringValue(); } },
                { "inCinemas", n => { InCinemas = n.GetDateTimeOffsetValue(); } },
                { "isAvailable", n => { IsAvailable = n.GetBoolValue(); } },
                { "keywords", n => { Keywords = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "lastSearchTime", n => { LastSearchTime = n.GetDateTimeOffsetValue(); } },
                { "minimumAvailability", n => { MinimumAvailability = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType>(); } },
                { "monitored", n => { Monitored = n.GetBoolValue(); } },
                { "movieFile", n => { MovieFile = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieFileResource>(global::Soenneker.Radarr.OpenApiClient.Models.MovieFileResource.CreateFromDiscriminatorValue); } },
                { "movieFileId", n => { MovieFileId = n.GetIntValue(); } },
                { "originalLanguage", n => { OriginalLanguage = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.Language>(global::Soenneker.Radarr.OpenApiClient.Models.Language.CreateFromDiscriminatorValue); } },
                { "originalTitle", n => { OriginalTitle = n.GetStringValue(); } },
                { "overview", n => { Overview = n.GetStringValue(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "physicalRelease", n => { PhysicalRelease = n.GetDateTimeOffsetValue(); } },
                { "physicalReleaseNote", n => { PhysicalReleaseNote = n.GetStringValue(); } },
                { "popularity", n => { Popularity = n.GetFloatValue(); } },
                { "qualityProfileId", n => { QualityProfileId = n.GetIntValue(); } },
                { "ratings", n => { Ratings = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.Ratings>(global::Soenneker.Radarr.OpenApiClient.Models.Ratings.CreateFromDiscriminatorValue); } },
                { "releaseDate", n => { ReleaseDate = n.GetDateTimeOffsetValue(); } },
                { "remotePoster", n => { RemotePoster = n.GetStringValue(); } },
                { "rootFolderPath", n => { RootFolderPath = n.GetStringValue(); } },
                { "runtime", n => { Runtime = n.GetIntValue(); } },
                { "secondaryYear", n => { SecondaryYear = n.GetIntValue(); } },
                { "secondaryYearSourceId", n => { SecondaryYearSourceId = n.GetIntValue(); } },
                { "sizeOnDisk", n => { SizeOnDisk = n.GetLongValue(); } },
                { "sortTitle", n => { SortTitle = n.GetStringValue(); } },
                { "statistics", n => { Statistics = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieStatisticsResource>(global::Soenneker.Radarr.OpenApiClient.Models.MovieStatisticsResource.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType>(); } },
                { "studio", n => { Studio = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "titleSlug", n => { TitleSlug = n.GetStringValue(); } },
                { "tmdbId", n => { TmdbId = n.GetIntValue(); } },
                { "website", n => { Website = n.GetStringValue(); } },
                { "year", n => { Year = n.GetIntValue(); } },
                { "youTubeTrailerId", n => { YouTubeTrailerId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("added", Added);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.AddMovieOptions>("addOptions", AddOptions);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.AlternativeTitleResource>("alternateTitles", AlternateTitles);
            writer.WriteStringValue("certification", Certification);
            writer.WriteStringValue("cleanTitle", CleanTitle);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieCollectionResource>("collection", Collection);
            writer.WriteDateTimeOffsetValue("digitalRelease", DigitalRelease);
            writer.WriteStringValue("folder", Folder);
            writer.WriteStringValue("folderName", FolderName);
            writer.WriteCollectionOfPrimitiveValues<string>("genres", Genres);
            writer.WriteBoolValue("hasFile", HasFile);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.MediaCover>("images", Images);
            writer.WriteStringValue("imdbId", ImdbId);
            writer.WriteDateTimeOffsetValue("inCinemas", InCinemas);
            writer.WriteBoolValue("isAvailable", IsAvailable);
            writer.WriteCollectionOfPrimitiveValues<string>("keywords", Keywords);
            writer.WriteDateTimeOffsetValue("lastSearchTime", LastSearchTime);
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType>("minimumAvailability", MinimumAvailability);
            writer.WriteBoolValue("monitored", Monitored);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieFileResource>("movieFile", MovieFile);
            writer.WriteIntValue("movieFileId", MovieFileId);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.Language>("originalLanguage", OriginalLanguage);
            writer.WriteStringValue("originalTitle", OriginalTitle);
            writer.WriteStringValue("overview", Overview);
            writer.WriteStringValue("path", Path);
            writer.WriteDateTimeOffsetValue("physicalRelease", PhysicalRelease);
            writer.WriteStringValue("physicalReleaseNote", PhysicalReleaseNote);
            writer.WriteFloatValue("popularity", Popularity);
            writer.WriteIntValue("qualityProfileId", QualityProfileId);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.Ratings>("ratings", Ratings);
            writer.WriteDateTimeOffsetValue("releaseDate", ReleaseDate);
            writer.WriteStringValue("remotePoster", RemotePoster);
            writer.WriteStringValue("rootFolderPath", RootFolderPath);
            writer.WriteIntValue("runtime", Runtime);
            writer.WriteIntValue("secondaryYear", SecondaryYear);
            writer.WriteIntValue("secondaryYearSourceId", SecondaryYearSourceId);
            writer.WriteLongValue("sizeOnDisk", SizeOnDisk);
            writer.WriteStringValue("sortTitle", SortTitle);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieStatisticsResource>("statistics", Statistics);
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieStatusType>("status", Status);
            writer.WriteStringValue("studio", Studio);
            writer.WriteCollectionOfPrimitiveValues<int?>("tags", Tags);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("titleSlug", TitleSlug);
            writer.WriteIntValue("tmdbId", TmdbId);
            writer.WriteStringValue("website", Website);
            writer.WriteIntValue("year", Year);
            writer.WriteStringValue("youTubeTrailerId", YouTubeTrailerId);
        }
    }
}
#pragma warning restore CS0618
