// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MovieFileResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The customFormats property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Radarr.OpenApiClient.Models.CustomFormatResource>? CustomFormats { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Radarr.OpenApiClient.Models.CustomFormatResource> CustomFormats { get; set; }
#endif
        /// <summary>The customFormatScore property</summary>
        public int? CustomFormatScore { get; set; }
        /// <summary>The dateAdded property</summary>
        public DateTimeOffset? DateAdded { get; set; }
        /// <summary>The edition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Edition { get; set; }
#nullable restore
#else
        public string Edition { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The indexerFlags property</summary>
        public int? IndexerFlags { get; set; }
        /// <summary>The languages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Radarr.OpenApiClient.Models.Language>? Languages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Radarr.OpenApiClient.Models.Language> Languages { get; set; }
#endif
        /// <summary>The mediaInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.MediaInfoResource? MediaInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.MediaInfoResource MediaInfo { get; set; }
#endif
        /// <summary>The movieId property</summary>
        public int? MovieId { get; set; }
        /// <summary>The originalFilePath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalFilePath { get; set; }
#nullable restore
#else
        public string OriginalFilePath { get; set; }
#endif
        /// <summary>The path property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The quality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.QualityModel? Quality { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.QualityModel Quality { get; set; }
#endif
        /// <summary>The qualityCutoffNotMet property</summary>
        public bool? QualityCutoffNotMet { get; set; }
        /// <summary>The relativePath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RelativePath { get; set; }
#nullable restore
#else
        public string RelativePath { get; set; }
#endif
        /// <summary>The releaseGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReleaseGroup { get; set; }
#nullable restore
#else
        public string ReleaseGroup { get; set; }
#endif
        /// <summary>The sceneName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SceneName { get; set; }
#nullable restore
#else
        public string SceneName { get; set; }
#endif
        /// <summary>The size property</summary>
        public long? Size { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.MovieFileResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.MovieFileResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.MovieFileResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customFormatScore", n => { CustomFormatScore = n.GetIntValue(); } },
                { "customFormats", n => { CustomFormats = n.GetCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.CustomFormatResource>(global::Soenneker.Radarr.OpenApiClient.Models.CustomFormatResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "dateAdded", n => { DateAdded = n.GetDateTimeOffsetValue(); } },
                { "edition", n => { Edition = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "indexerFlags", n => { IndexerFlags = n.GetIntValue(); } },
                { "languages", n => { Languages = n.GetCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.Language>(global::Soenneker.Radarr.OpenApiClient.Models.Language.CreateFromDiscriminatorValue)?.AsList(); } },
                { "mediaInfo", n => { MediaInfo = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.MediaInfoResource>(global::Soenneker.Radarr.OpenApiClient.Models.MediaInfoResource.CreateFromDiscriminatorValue); } },
                { "movieId", n => { MovieId = n.GetIntValue(); } },
                { "originalFilePath", n => { OriginalFilePath = n.GetStringValue(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "quality", n => { Quality = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.QualityModel>(global::Soenneker.Radarr.OpenApiClient.Models.QualityModel.CreateFromDiscriminatorValue); } },
                { "qualityCutoffNotMet", n => { QualityCutoffNotMet = n.GetBoolValue(); } },
                { "relativePath", n => { RelativePath = n.GetStringValue(); } },
                { "releaseGroup", n => { ReleaseGroup = n.GetStringValue(); } },
                { "sceneName", n => { SceneName = n.GetStringValue(); } },
                { "size", n => { Size = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.CustomFormatResource>("customFormats", CustomFormats);
            writer.WriteIntValue("customFormatScore", CustomFormatScore);
            writer.WriteDateTimeOffsetValue("dateAdded", DateAdded);
            writer.WriteStringValue("edition", Edition);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("indexerFlags", IndexerFlags);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.Language>("languages", Languages);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.MediaInfoResource>("mediaInfo", MediaInfo);
            writer.WriteIntValue("movieId", MovieId);
            writer.WriteStringValue("originalFilePath", OriginalFilePath);
            writer.WriteStringValue("path", Path);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.QualityModel>("quality", Quality);
            writer.WriteBoolValue("qualityCutoffNotMet", QualityCutoffNotMet);
            writer.WriteStringValue("relativePath", RelativePath);
            writer.WriteStringValue("releaseGroup", ReleaseGroup);
            writer.WriteStringValue("sceneName", SceneName);
            writer.WriteLongValue("size", Size);
        }
    }
}
#pragma warning restore CS0618
