// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MovieRuntimeFormatType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "hoursMinutes")]
        #pragma warning disable CS1591
        HoursMinutes,
        #pragma warning restore CS1591
        [EnumMember(Value = "minutes")]
        #pragma warning disable CS1591
        Minutes,
        #pragma warning restore CS1591
    }
}
