// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MovieFileListResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The edition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Edition { get; set; }
#nullable restore
#else
        public string Edition { get; set; }
#endif
        /// <summary>The indexerFlags property</summary>
        public int? IndexerFlags { get; set; }
        /// <summary>The languages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Radarr.OpenApiClient.Models.Language>? Languages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Radarr.OpenApiClient.Models.Language> Languages { get; set; }
#endif
        /// <summary>The movieFileIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? MovieFileIds { get; set; }
#nullable restore
#else
        public List<int?> MovieFileIds { get; set; }
#endif
        /// <summary>The quality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.QualityModel? Quality { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.QualityModel Quality { get; set; }
#endif
        /// <summary>The releaseGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReleaseGroup { get; set; }
#nullable restore
#else
        public string ReleaseGroup { get; set; }
#endif
        /// <summary>The sceneName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SceneName { get; set; }
#nullable restore
#else
        public string SceneName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.MovieFileListResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.MovieFileListResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.MovieFileListResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "edition", n => { Edition = n.GetStringValue(); } },
                { "indexerFlags", n => { IndexerFlags = n.GetIntValue(); } },
                { "languages", n => { Languages = n.GetCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.Language>(global::Soenneker.Radarr.OpenApiClient.Models.Language.CreateFromDiscriminatorValue)?.AsList(); } },
                { "movieFileIds", n => { MovieFileIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "quality", n => { Quality = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.QualityModel>(global::Soenneker.Radarr.OpenApiClient.Models.QualityModel.CreateFromDiscriminatorValue); } },
                { "releaseGroup", n => { ReleaseGroup = n.GetStringValue(); } },
                { "sceneName", n => { SceneName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("edition", Edition);
            writer.WriteIntValue("indexerFlags", IndexerFlags);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.Language>("languages", Languages);
            writer.WriteCollectionOfPrimitiveValues<int?>("movieFileIds", MovieFileIds);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.QualityModel>("quality", Quality);
            writer.WriteStringValue("releaseGroup", ReleaseGroup);
            writer.WriteStringValue("sceneName", SceneName);
        }
    }
}
#pragma warning restore CS0618
