// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MovieHistoryEventType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "grabbed")]
        #pragma warning disable CS1591
        Grabbed,
        #pragma warning restore CS1591
        [EnumMember(Value = "downloadFolderImported")]
        #pragma warning disable CS1591
        DownloadFolderImported,
        #pragma warning restore CS1591
        [EnumMember(Value = "downloadFailed")]
        #pragma warning disable CS1591
        DownloadFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "movieFileDeleted")]
        #pragma warning disable CS1591
        MovieFileDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "movieFolderImported")]
        #pragma warning disable CS1591
        MovieFolderImported,
        #pragma warning restore CS1591
        [EnumMember(Value = "movieFileRenamed")]
        #pragma warning disable CS1591
        MovieFileRenamed,
        #pragma warning restore CS1591
        [EnumMember(Value = "downloadIgnored")]
        #pragma warning disable CS1591
        DownloadIgnored,
        #pragma warning restore CS1591
    }
}
