// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MovieStatisticsResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The movieFileCount property</summary>
        public int? MovieFileCount { get; set; }
        /// <summary>The releaseGroups property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ReleaseGroups { get; set; }
#nullable restore
#else
        public List<string> ReleaseGroups { get; set; }
#endif
        /// <summary>The sizeOnDisk property</summary>
        public long? SizeOnDisk { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.MovieStatisticsResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.MovieStatisticsResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.MovieStatisticsResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "movieFileCount", n => { MovieFileCount = n.GetIntValue(); } },
                { "releaseGroups", n => { ReleaseGroups = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "sizeOnDisk", n => { SizeOnDisk = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("movieFileCount", MovieFileCount);
            writer.WriteCollectionOfPrimitiveValues<string>("releaseGroups", ReleaseGroups);
            writer.WriteLongValue("sizeOnDisk", SizeOnDisk);
        }
    }
}
#pragma warning restore CS0618
