// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NamingConfigResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The colonReplacementFormat property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.ColonReplacementFormat? ColonReplacementFormat { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The movieFolderFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MovieFolderFormat { get; set; }
#nullable restore
#else
        public string MovieFolderFormat { get; set; }
#endif
        /// <summary>The renameMovies property</summary>
        public bool? RenameMovies { get; set; }
        /// <summary>The replaceIllegalCharacters property</summary>
        public bool? ReplaceIllegalCharacters { get; set; }
        /// <summary>The standardMovieFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StandardMovieFormat { get; set; }
#nullable restore
#else
        public string StandardMovieFormat { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.NamingConfigResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.NamingConfigResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.NamingConfigResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "colonReplacementFormat", n => { ColonReplacementFormat = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.ColonReplacementFormat>(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "movieFolderFormat", n => { MovieFolderFormat = n.GetStringValue(); } },
                { "renameMovies", n => { RenameMovies = n.GetBoolValue(); } },
                { "replaceIllegalCharacters", n => { ReplaceIllegalCharacters = n.GetBoolValue(); } },
                { "standardMovieFormat", n => { StandardMovieFormat = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.ColonReplacementFormat>("colonReplacementFormat", ColonReplacementFormat);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("movieFolderFormat", MovieFolderFormat);
            writer.WriteBoolValue("renameMovies", RenameMovies);
            writer.WriteBoolValue("replaceIllegalCharacters", ReplaceIllegalCharacters);
            writer.WriteStringValue("standardMovieFormat", StandardMovieFormat);
        }
    }
}
#pragma warning restore CS0618
