// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ParsedMovieInfo : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The edition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Edition { get; set; }
#nullable restore
#else
        public string Edition { get; set; }
#endif
        /// <summary>The hardcodedSubs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HardcodedSubs { get; set; }
#nullable restore
#else
        public string HardcodedSubs { get; set; }
#endif
        /// <summary>The imdbId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImdbId { get; set; }
#nullable restore
#else
        public string ImdbId { get; set; }
#endif
        /// <summary>The languages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Radarr.OpenApiClient.Models.Language>? Languages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Radarr.OpenApiClient.Models.Language> Languages { get; set; }
#endif
        /// <summary>The movieTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MovieTitle { get; private set; }
#nullable restore
#else
        public string MovieTitle { get; private set; }
#endif
        /// <summary>The movieTitles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MovieTitles { get; set; }
#nullable restore
#else
        public List<string> MovieTitles { get; set; }
#endif
        /// <summary>The originalTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalTitle { get; set; }
#nullable restore
#else
        public string OriginalTitle { get; set; }
#endif
        /// <summary>The primaryMovieTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryMovieTitle { get; private set; }
#nullable restore
#else
        public string PrimaryMovieTitle { get; private set; }
#endif
        /// <summary>The quality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.QualityModel? Quality { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.QualityModel Quality { get; set; }
#endif
        /// <summary>The releaseGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReleaseGroup { get; set; }
#nullable restore
#else
        public string ReleaseGroup { get; set; }
#endif
        /// <summary>The releaseHash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReleaseHash { get; set; }
#nullable restore
#else
        public string ReleaseHash { get; set; }
#endif
        /// <summary>The releaseTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReleaseTitle { get; set; }
#nullable restore
#else
        public string ReleaseTitle { get; set; }
#endif
        /// <summary>The simpleReleaseTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SimpleReleaseTitle { get; set; }
#nullable restore
#else
        public string SimpleReleaseTitle { get; set; }
#endif
        /// <summary>The tmdbId property</summary>
        public int? TmdbId { get; set; }
        /// <summary>The year property</summary>
        public int? Year { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.ParsedMovieInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.ParsedMovieInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.ParsedMovieInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "edition", n => { Edition = n.GetStringValue(); } },
                { "hardcodedSubs", n => { HardcodedSubs = n.GetStringValue(); } },
                { "imdbId", n => { ImdbId = n.GetStringValue(); } },
                { "languages", n => { Languages = n.GetCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.Language>(global::Soenneker.Radarr.OpenApiClient.Models.Language.CreateFromDiscriminatorValue)?.AsList(); } },
                { "movieTitle", n => { MovieTitle = n.GetStringValue(); } },
                { "movieTitles", n => { MovieTitles = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "originalTitle", n => { OriginalTitle = n.GetStringValue(); } },
                { "primaryMovieTitle", n => { PrimaryMovieTitle = n.GetStringValue(); } },
                { "quality", n => { Quality = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.QualityModel>(global::Soenneker.Radarr.OpenApiClient.Models.QualityModel.CreateFromDiscriminatorValue); } },
                { "releaseGroup", n => { ReleaseGroup = n.GetStringValue(); } },
                { "releaseHash", n => { ReleaseHash = n.GetStringValue(); } },
                { "releaseTitle", n => { ReleaseTitle = n.GetStringValue(); } },
                { "simpleReleaseTitle", n => { SimpleReleaseTitle = n.GetStringValue(); } },
                { "tmdbId", n => { TmdbId = n.GetIntValue(); } },
                { "year", n => { Year = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("edition", Edition);
            writer.WriteStringValue("hardcodedSubs", HardcodedSubs);
            writer.WriteStringValue("imdbId", ImdbId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.Language>("languages", Languages);
            writer.WriteCollectionOfPrimitiveValues<string>("movieTitles", MovieTitles);
            writer.WriteStringValue("originalTitle", OriginalTitle);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.QualityModel>("quality", Quality);
            writer.WriteStringValue("releaseGroup", ReleaseGroup);
            writer.WriteStringValue("releaseHash", ReleaseHash);
            writer.WriteStringValue("releaseTitle", ReleaseTitle);
            writer.WriteStringValue("simpleReleaseTitle", SimpleReleaseTitle);
            writer.WriteIntValue("tmdbId", TmdbId);
            writer.WriteIntValue("year", Year);
        }
    }
}
#pragma warning restore CS0618
