// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum QualitySource
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "cam")]
        #pragma warning disable CS1591
        Cam,
        #pragma warning restore CS1591
        [EnumMember(Value = "telesync")]
        #pragma warning disable CS1591
        Telesync,
        #pragma warning restore CS1591
        [EnumMember(Value = "telecine")]
        #pragma warning disable CS1591
        Telecine,
        #pragma warning restore CS1591
        [EnumMember(Value = "workprint")]
        #pragma warning disable CS1591
        Workprint,
        #pragma warning restore CS1591
        [EnumMember(Value = "dvd")]
        #pragma warning disable CS1591
        Dvd,
        #pragma warning restore CS1591
        [EnumMember(Value = "tv")]
        #pragma warning disable CS1591
        Tv,
        #pragma warning restore CS1591
        [EnumMember(Value = "webdl")]
        #pragma warning disable CS1591
        Webdl,
        #pragma warning restore CS1591
        [EnumMember(Value = "webrip")]
        #pragma warning disable CS1591
        Webrip,
        #pragma warning restore CS1591
        [EnumMember(Value = "bluray")]
        #pragma warning disable CS1591
        Bluray,
        #pragma warning restore CS1591
    }
}
