// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QueueResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The added property</summary>
        public DateTimeOffset? Added { get; set; }
        /// <summary>The customFormats property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Radarr.OpenApiClient.Models.CustomFormatResource>? CustomFormats { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Radarr.OpenApiClient.Models.CustomFormatResource> CustomFormats { get; set; }
#endif
        /// <summary>The customFormatScore property</summary>
        public int? CustomFormatScore { get; set; }
        /// <summary>The downloadClient property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DownloadClient { get; set; }
#nullable restore
#else
        public string DownloadClient { get; set; }
#endif
        /// <summary>The downloadClientHasPostImportCategory property</summary>
        public bool? DownloadClientHasPostImportCategory { get; set; }
        /// <summary>The downloadId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DownloadId { get; set; }
#nullable restore
#else
        public string DownloadId { get; set; }
#endif
        /// <summary>The errorMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorMessage { get; set; }
#nullable restore
#else
        public string ErrorMessage { get; set; }
#endif
        /// <summary>The estimatedCompletionTime property</summary>
        public DateTimeOffset? EstimatedCompletionTime { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The indexer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Indexer { get; set; }
#nullable restore
#else
        public string Indexer { get; set; }
#endif
        /// <summary>The languages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Radarr.OpenApiClient.Models.Language>? Languages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Radarr.OpenApiClient.Models.Language> Languages { get; set; }
#endif
        /// <summary>The movie property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.MovieResource? Movie { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.MovieResource Movie { get; set; }
#endif
        /// <summary>The movieId property</summary>
        public int? MovieId { get; set; }
        /// <summary>The outputPath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OutputPath { get; set; }
#nullable restore
#else
        public string OutputPath { get; set; }
#endif
        /// <summary>The protocol property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.DownloadProtocol? Protocol { get; set; }
        /// <summary>The quality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.QualityModel? Quality { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.QualityModel Quality { get; set; }
#endif
        /// <summary>The size property</summary>
        public double? Size { get; set; }
        /// <summary>The sizeleft property</summary>
        [Obsolete("")]
        public double? Sizeleft { get; set; }
        /// <summary>The status property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.QueueStatus? Status { get; set; }
        /// <summary>The statusMessages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Radarr.OpenApiClient.Models.TrackedDownloadStatusMessage>? StatusMessages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Radarr.OpenApiClient.Models.TrackedDownloadStatusMessage> StatusMessages { get; set; }
#endif
        /// <summary>The timeleft property</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timeleft { get; set; }
#nullable restore
#else
        public string Timeleft { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The trackedDownloadState property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.TrackedDownloadState? TrackedDownloadState { get; set; }
        /// <summary>The trackedDownloadStatus property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.TrackedDownloadStatus? TrackedDownloadStatus { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.QueueResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.QueueResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.QueueResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "added", n => { Added = n.GetDateTimeOffsetValue(); } },
                { "customFormatScore", n => { CustomFormatScore = n.GetIntValue(); } },
                { "customFormats", n => { CustomFormats = n.GetCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.CustomFormatResource>(global::Soenneker.Radarr.OpenApiClient.Models.CustomFormatResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "downloadClient", n => { DownloadClient = n.GetStringValue(); } },
                { "downloadClientHasPostImportCategory", n => { DownloadClientHasPostImportCategory = n.GetBoolValue(); } },
                { "downloadId", n => { DownloadId = n.GetStringValue(); } },
                { "errorMessage", n => { ErrorMessage = n.GetStringValue(); } },
                { "estimatedCompletionTime", n => { EstimatedCompletionTime = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "indexer", n => { Indexer = n.GetStringValue(); } },
                { "languages", n => { Languages = n.GetCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.Language>(global::Soenneker.Radarr.OpenApiClient.Models.Language.CreateFromDiscriminatorValue)?.AsList(); } },
                { "movie", n => { Movie = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieResource>(global::Soenneker.Radarr.OpenApiClient.Models.MovieResource.CreateFromDiscriminatorValue); } },
                { "movieId", n => { MovieId = n.GetIntValue(); } },
                { "outputPath", n => { OutputPath = n.GetStringValue(); } },
                { "protocol", n => { Protocol = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.DownloadProtocol>(); } },
                { "quality", n => { Quality = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.QualityModel>(global::Soenneker.Radarr.OpenApiClient.Models.QualityModel.CreateFromDiscriminatorValue); } },
                { "size", n => { Size = n.GetDoubleValue(); } },
                { "sizeleft", n => { Sizeleft = n.GetDoubleValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.QueueStatus>(); } },
                { "statusMessages", n => { StatusMessages = n.GetCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.TrackedDownloadStatusMessage>(global::Soenneker.Radarr.OpenApiClient.Models.TrackedDownloadStatusMessage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "timeleft", n => { Timeleft = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "trackedDownloadState", n => { TrackedDownloadState = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.TrackedDownloadState>(); } },
                { "trackedDownloadStatus", n => { TrackedDownloadStatus = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.TrackedDownloadStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("added", Added);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.CustomFormatResource>("customFormats", CustomFormats);
            writer.WriteIntValue("customFormatScore", CustomFormatScore);
            writer.WriteStringValue("downloadClient", DownloadClient);
            writer.WriteBoolValue("downloadClientHasPostImportCategory", DownloadClientHasPostImportCategory);
            writer.WriteStringValue("downloadId", DownloadId);
            writer.WriteStringValue("errorMessage", ErrorMessage);
            writer.WriteDateTimeOffsetValue("estimatedCompletionTime", EstimatedCompletionTime);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("indexer", Indexer);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.Language>("languages", Languages);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.MovieResource>("movie", Movie);
            writer.WriteIntValue("movieId", MovieId);
            writer.WriteStringValue("outputPath", OutputPath);
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.DownloadProtocol>("protocol", Protocol);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.QualityModel>("quality", Quality);
            writer.WriteDoubleValue("size", Size);
            writer.WriteDoubleValue("sizeleft", Sizeleft);
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.QueueStatus>("status", Status);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.TrackedDownloadStatusMessage>("statusMessages", StatusMessages);
            writer.WriteStringValue("timeleft", Timeleft);
            writer.WriteStringValue("title", Title);
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.TrackedDownloadState>("trackedDownloadState", TrackedDownloadState);
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.TrackedDownloadStatus>("trackedDownloadStatus", TrackedDownloadStatus);
        }
    }
}
#pragma warning restore CS0618
