// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Ratings : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The imdb property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.RatingChild? Imdb { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.RatingChild Imdb { get; set; }
#endif
        /// <summary>The metacritic property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.RatingChild? Metacritic { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.RatingChild Metacritic { get; set; }
#endif
        /// <summary>The rottenTomatoes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.RatingChild? RottenTomatoes { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.RatingChild RottenTomatoes { get; set; }
#endif
        /// <summary>The tmdb property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.RatingChild? Tmdb { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.RatingChild Tmdb { get; set; }
#endif
        /// <summary>The trakt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.RatingChild? Trakt { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.RatingChild Trakt { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.Ratings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.Ratings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.Ratings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "imdb", n => { Imdb = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.RatingChild>(global::Soenneker.Radarr.OpenApiClient.Models.RatingChild.CreateFromDiscriminatorValue); } },
                { "metacritic", n => { Metacritic = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.RatingChild>(global::Soenneker.Radarr.OpenApiClient.Models.RatingChild.CreateFromDiscriminatorValue); } },
                { "rottenTomatoes", n => { RottenTomatoes = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.RatingChild>(global::Soenneker.Radarr.OpenApiClient.Models.RatingChild.CreateFromDiscriminatorValue); } },
                { "tmdb", n => { Tmdb = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.RatingChild>(global::Soenneker.Radarr.OpenApiClient.Models.RatingChild.CreateFromDiscriminatorValue); } },
                { "trakt", n => { Trakt = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.RatingChild>(global::Soenneker.Radarr.OpenApiClient.Models.RatingChild.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.RatingChild>("imdb", Imdb);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.RatingChild>("metacritic", Metacritic);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.RatingChild>("rottenTomatoes", RottenTomatoes);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.RatingChild>("tmdb", Tmdb);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.RatingChild>("trakt", Trakt);
        }
    }
}
#pragma warning restore CS0618
