// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReleaseResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The age property</summary>
        public int? Age { get; set; }
        /// <summary>The ageHours property</summary>
        public double? AgeHours { get; set; }
        /// <summary>The ageMinutes property</summary>
        public double? AgeMinutes { get; set; }
        /// <summary>The approved property</summary>
        public bool? Approved { get; set; }
        /// <summary>The commentUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommentUrl { get; set; }
#nullable restore
#else
        public string CommentUrl { get; set; }
#endif
        /// <summary>The customFormats property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Radarr.OpenApiClient.Models.CustomFormatResource>? CustomFormats { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Radarr.OpenApiClient.Models.CustomFormatResource> CustomFormats { get; set; }
#endif
        /// <summary>The customFormatScore property</summary>
        public int? CustomFormatScore { get; set; }
        /// <summary>The downloadAllowed property</summary>
        public bool? DownloadAllowed { get; set; }
        /// <summary>The downloadClient property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DownloadClient { get; set; }
#nullable restore
#else
        public string DownloadClient { get; set; }
#endif
        /// <summary>The downloadClientId property</summary>
        public int? DownloadClientId { get; set; }
        /// <summary>The downloadUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DownloadUrl { get; set; }
#nullable restore
#else
        public string DownloadUrl { get; set; }
#endif
        /// <summary>The edition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Edition { get; set; }
#nullable restore
#else
        public string Edition { get; set; }
#endif
        /// <summary>The guid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Guid { get; set; }
#nullable restore
#else
        public string Guid { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The imdbId property</summary>
        public int? ImdbId { get; set; }
        /// <summary>The indexer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Indexer { get; set; }
#nullable restore
#else
        public string Indexer { get; set; }
#endif
        /// <summary>The indexerFlags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? IndexerFlags { get; set; }
#nullable restore
#else
        public UntypedNode IndexerFlags { get; set; }
#endif
        /// <summary>The indexerId property</summary>
        public int? IndexerId { get; set; }
        /// <summary>The infoHash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InfoHash { get; set; }
#nullable restore
#else
        public string InfoHash { get; set; }
#endif
        /// <summary>The infoUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InfoUrl { get; set; }
#nullable restore
#else
        public string InfoUrl { get; set; }
#endif
        /// <summary>The languages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Radarr.OpenApiClient.Models.Language>? Languages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Radarr.OpenApiClient.Models.Language> Languages { get; set; }
#endif
        /// <summary>The leechers property</summary>
        public int? Leechers { get; set; }
        /// <summary>The magnetUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MagnetUrl { get; set; }
#nullable restore
#else
        public string MagnetUrl { get; set; }
#endif
        /// <summary>The mappedMovieId property</summary>
        public int? MappedMovieId { get; set; }
        /// <summary>The movieId property</summary>
        public int? MovieId { get; set; }
        /// <summary>The movieRequested property</summary>
        public bool? MovieRequested { get; set; }
        /// <summary>The movieTitles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MovieTitles { get; set; }
#nullable restore
#else
        public List<string> MovieTitles { get; set; }
#endif
        /// <summary>The protocol property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Models.DownloadProtocol? Protocol { get; set; }
        /// <summary>The publishDate property</summary>
        public DateTimeOffset? PublishDate { get; set; }
        /// <summary>The quality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Radarr.OpenApiClient.Models.QualityModel? Quality { get; set; }
#nullable restore
#else
        public global::Soenneker.Radarr.OpenApiClient.Models.QualityModel Quality { get; set; }
#endif
        /// <summary>The qualityWeight property</summary>
        public int? QualityWeight { get; set; }
        /// <summary>The rejected property</summary>
        public bool? Rejected { get; set; }
        /// <summary>The rejections property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Rejections { get; set; }
#nullable restore
#else
        public List<string> Rejections { get; set; }
#endif
        /// <summary>The releaseGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReleaseGroup { get; set; }
#nullable restore
#else
        public string ReleaseGroup { get; set; }
#endif
        /// <summary>The releaseHash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReleaseHash { get; set; }
#nullable restore
#else
        public string ReleaseHash { get; set; }
#endif
        /// <summary>The releaseWeight property</summary>
        public int? ReleaseWeight { get; set; }
        /// <summary>The sceneSource property</summary>
        public bool? SceneSource { get; set; }
        /// <summary>The seeders property</summary>
        public int? Seeders { get; set; }
        /// <summary>The shouldOverride property</summary>
        public bool? ShouldOverride { get; set; }
        /// <summary>The size property</summary>
        public long? Size { get; set; }
        /// <summary>The subGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubGroup { get; set; }
#nullable restore
#else
        public string SubGroup { get; set; }
#endif
        /// <summary>The temporarilyRejected property</summary>
        public bool? TemporarilyRejected { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The tmdbId property</summary>
        public int? TmdbId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.ReleaseResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Radarr.OpenApiClient.Models.ReleaseResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Radarr.OpenApiClient.Models.ReleaseResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "age", n => { Age = n.GetIntValue(); } },
                { "ageHours", n => { AgeHours = n.GetDoubleValue(); } },
                { "ageMinutes", n => { AgeMinutes = n.GetDoubleValue(); } },
                { "approved", n => { Approved = n.GetBoolValue(); } },
                { "commentUrl", n => { CommentUrl = n.GetStringValue(); } },
                { "customFormatScore", n => { CustomFormatScore = n.GetIntValue(); } },
                { "customFormats", n => { CustomFormats = n.GetCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.CustomFormatResource>(global::Soenneker.Radarr.OpenApiClient.Models.CustomFormatResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "downloadAllowed", n => { DownloadAllowed = n.GetBoolValue(); } },
                { "downloadClient", n => { DownloadClient = n.GetStringValue(); } },
                { "downloadClientId", n => { DownloadClientId = n.GetIntValue(); } },
                { "downloadUrl", n => { DownloadUrl = n.GetStringValue(); } },
                { "edition", n => { Edition = n.GetStringValue(); } },
                { "guid", n => { Guid = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "imdbId", n => { ImdbId = n.GetIntValue(); } },
                { "indexer", n => { Indexer = n.GetStringValue(); } },
                { "indexerFlags", n => { IndexerFlags = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "indexerId", n => { IndexerId = n.GetIntValue(); } },
                { "infoHash", n => { InfoHash = n.GetStringValue(); } },
                { "infoUrl", n => { InfoUrl = n.GetStringValue(); } },
                { "languages", n => { Languages = n.GetCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.Language>(global::Soenneker.Radarr.OpenApiClient.Models.Language.CreateFromDiscriminatorValue)?.AsList(); } },
                { "leechers", n => { Leechers = n.GetIntValue(); } },
                { "magnetUrl", n => { MagnetUrl = n.GetStringValue(); } },
                { "mappedMovieId", n => { MappedMovieId = n.GetIntValue(); } },
                { "movieId", n => { MovieId = n.GetIntValue(); } },
                { "movieRequested", n => { MovieRequested = n.GetBoolValue(); } },
                { "movieTitles", n => { MovieTitles = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "protocol", n => { Protocol = n.GetEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.DownloadProtocol>(); } },
                { "publishDate", n => { PublishDate = n.GetDateTimeOffsetValue(); } },
                { "quality", n => { Quality = n.GetObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.QualityModel>(global::Soenneker.Radarr.OpenApiClient.Models.QualityModel.CreateFromDiscriminatorValue); } },
                { "qualityWeight", n => { QualityWeight = n.GetIntValue(); } },
                { "rejected", n => { Rejected = n.GetBoolValue(); } },
                { "rejections", n => { Rejections = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "releaseGroup", n => { ReleaseGroup = n.GetStringValue(); } },
                { "releaseHash", n => { ReleaseHash = n.GetStringValue(); } },
                { "releaseWeight", n => { ReleaseWeight = n.GetIntValue(); } },
                { "sceneSource", n => { SceneSource = n.GetBoolValue(); } },
                { "seeders", n => { Seeders = n.GetIntValue(); } },
                { "shouldOverride", n => { ShouldOverride = n.GetBoolValue(); } },
                { "size", n => { Size = n.GetLongValue(); } },
                { "subGroup", n => { SubGroup = n.GetStringValue(); } },
                { "temporarilyRejected", n => { TemporarilyRejected = n.GetBoolValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "tmdbId", n => { TmdbId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("age", Age);
            writer.WriteDoubleValue("ageHours", AgeHours);
            writer.WriteDoubleValue("ageMinutes", AgeMinutes);
            writer.WriteBoolValue("approved", Approved);
            writer.WriteStringValue("commentUrl", CommentUrl);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.CustomFormatResource>("customFormats", CustomFormats);
            writer.WriteIntValue("customFormatScore", CustomFormatScore);
            writer.WriteBoolValue("downloadAllowed", DownloadAllowed);
            writer.WriteStringValue("downloadClient", DownloadClient);
            writer.WriteIntValue("downloadClientId", DownloadClientId);
            writer.WriteStringValue("downloadUrl", DownloadUrl);
            writer.WriteStringValue("edition", Edition);
            writer.WriteStringValue("guid", Guid);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("imdbId", ImdbId);
            writer.WriteStringValue("indexer", Indexer);
            writer.WriteObjectValue<UntypedNode>("indexerFlags", IndexerFlags);
            writer.WriteIntValue("indexerId", IndexerId);
            writer.WriteStringValue("infoHash", InfoHash);
            writer.WriteStringValue("infoUrl", InfoUrl);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Radarr.OpenApiClient.Models.Language>("languages", Languages);
            writer.WriteIntValue("leechers", Leechers);
            writer.WriteStringValue("magnetUrl", MagnetUrl);
            writer.WriteIntValue("mappedMovieId", MappedMovieId);
            writer.WriteIntValue("movieId", MovieId);
            writer.WriteBoolValue("movieRequested", MovieRequested);
            writer.WriteCollectionOfPrimitiveValues<string>("movieTitles", MovieTitles);
            writer.WriteEnumValue<global::Soenneker.Radarr.OpenApiClient.Models.DownloadProtocol>("protocol", Protocol);
            writer.WriteDateTimeOffsetValue("publishDate", PublishDate);
            writer.WriteObjectValue<global::Soenneker.Radarr.OpenApiClient.Models.QualityModel>("quality", Quality);
            writer.WriteIntValue("qualityWeight", QualityWeight);
            writer.WriteBoolValue("rejected", Rejected);
            writer.WriteCollectionOfPrimitiveValues<string>("rejections", Rejections);
            writer.WriteStringValue("releaseGroup", ReleaseGroup);
            writer.WriteStringValue("releaseHash", ReleaseHash);
            writer.WriteIntValue("releaseWeight", ReleaseWeight);
            writer.WriteBoolValue("sceneSource", SceneSource);
            writer.WriteIntValue("seeders", Seeders);
            writer.WriteBoolValue("shouldOverride", ShouldOverride);
            writer.WriteLongValue("size", Size);
            writer.WriteStringValue("subGroup", SubGroup);
            writer.WriteBoolValue("temporarilyRejected", TemporarilyRejected);
            writer.WriteStringValue("title", Title);
            writer.WriteIntValue("tmdbId", TmdbId);
        }
    }
}
#pragma warning restore CS0618
