// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SourceType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "tmdb")]
        #pragma warning disable CS1591
        Tmdb,
        #pragma warning restore CS1591
        [EnumMember(Value = "mappings")]
        #pragma warning disable CS1591
        Mappings,
        #pragma warning restore CS1591
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "indexer")]
        #pragma warning disable CS1591
        Indexer,
        #pragma warning restore CS1591
    }
}
