// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Radarr.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TMDbCountryCode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "au")]
        #pragma warning disable CS1591
        Au,
        #pragma warning restore CS1591
        [EnumMember(Value = "br")]
        #pragma warning disable CS1591
        Br,
        #pragma warning restore CS1591
        [EnumMember(Value = "ca")]
        #pragma warning disable CS1591
        Ca,
        #pragma warning restore CS1591
        [EnumMember(Value = "fr")]
        #pragma warning disable CS1591
        Fr,
        #pragma warning restore CS1591
        [EnumMember(Value = "de")]
        #pragma warning disable CS1591
        De,
        #pragma warning restore CS1591
        [EnumMember(Value = "gb")]
        #pragma warning disable CS1591
        Gb,
        #pragma warning restore CS1591
        [EnumMember(Value = "in")]
        #pragma warning disable CS1591
        In,
        #pragma warning restore CS1591
        [EnumMember(Value = "ie")]
        #pragma warning disable CS1591
        Ie,
        #pragma warning restore CS1591
        [EnumMember(Value = "it")]
        #pragma warning disable CS1591
        It,
        #pragma warning restore CS1591
        [EnumMember(Value = "nz")]
        #pragma warning disable CS1591
        Nz,
        #pragma warning restore CS1591
        [EnumMember(Value = "ro")]
        #pragma warning disable CS1591
        Ro,
        #pragma warning restore CS1591
        [EnumMember(Value = "es")]
        #pragma warning disable CS1591
        Es,
        #pragma warning restore CS1591
        [EnumMember(Value = "us")]
        #pragma warning disable CS1591
        Us,
        #pragma warning restore CS1591
    }
}
