// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Editor;
using Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Import;
using Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Item;
using Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Lookup;
using Soenneker.Radarr.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Radarr.OpenApiClient.Api.V3.Movie
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\movie
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MovieRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The editor property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Editor.EditorRequestBuilder Editor
        {
            get => new global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Editor.EditorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The import property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Import.ImportRequestBuilder Import
        {
            get => new global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Import.ImportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lookup property</summary>
        public global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Lookup.LookupRequestBuilder Lookup
        {
            get => new global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Lookup.LookupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Radarr.OpenApiClient.api.v3.movie.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Item.MovieItemRequestBuilder"/></returns>
        public global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Item.MovieItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Item.MovieItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.MovieRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MovieRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/movie{?excludeLocalCovers*,languageId*,tmdbId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.MovieRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MovieRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/movie{?excludeLocalCovers*,languageId*,tmdbId*}", rawUrl)
        {
        }
        /// <returns>A List&lt;global::Soenneker.Radarr.OpenApiClient.Models.MovieResource&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Radarr.OpenApiClient.Models.MovieResource>?> GetAsync(Action<RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.MovieRequestBuilder.MovieRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Radarr.OpenApiClient.Models.MovieResource>> GetAsync(Action<RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.MovieRequestBuilder.MovieRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Radarr.OpenApiClient.Models.MovieResource>(requestInfo, global::Soenneker.Radarr.OpenApiClient.Models.MovieResource.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.MovieResource"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Radarr.OpenApiClient.Models.MovieResource?> PostAsync(global::Soenneker.Radarr.OpenApiClient.Models.MovieResource body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Radarr.OpenApiClient.Models.MovieResource> PostAsync(global::Soenneker.Radarr.OpenApiClient.Models.MovieResource body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Radarr.OpenApiClient.Models.MovieResource>(requestInfo, global::Soenneker.Radarr.OpenApiClient.Models.MovieResource.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.MovieRequestBuilder.MovieRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.MovieRequestBuilder.MovieRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Radarr.OpenApiClient.Models.MovieResource body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Radarr.OpenApiClient.Models.MovieResource body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.MovieRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.MovieRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.MovieRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class MovieRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("excludeLocalCovers")]
            public bool? ExcludeLocalCovers { get; set; }
            [QueryParameter("languageId")]
            public int? LanguageId { get; set; }
            [QueryParameter("tmdbId")]
            public int? TmdbId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MovieRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.MovieRequestBuilder.MovieRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MovieRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
