// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Radarr.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Radarr.OpenApiClient.Api.V3.Config.Naming.Examples
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\config\naming\examples
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExamplesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Radarr.OpenApiClient.Api.V3.Config.Naming.Examples.ExamplesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExamplesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/config/naming/examples{?colonReplacementFormat*,id*,movieFolderFormat*,renameMovies*,replaceIllegalCharacters*,resourceName*,standardMovieFormat*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Radarr.OpenApiClient.Api.V3.Config.Naming.Examples.ExamplesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExamplesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/config/naming/examples{?colonReplacementFormat*,id*,movieFolderFormat*,renameMovies*,replaceIllegalCharacters*,resourceName*,standardMovieFormat*}", rawUrl)
        {
        }
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Api.V3.Config.Naming.Examples.ExamplesRequestBuilder.ExamplesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Api.V3.Config.Naming.Examples.ExamplesRequestBuilder.ExamplesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Api.V3.Config.Naming.Examples.ExamplesRequestBuilder.ExamplesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Api.V3.Config.Naming.Examples.ExamplesRequestBuilder.ExamplesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Api.V3.Config.Naming.Examples.ExamplesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Radarr.OpenApiClient.Api.V3.Config.Naming.Examples.ExamplesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Radarr.OpenApiClient.Api.V3.Config.Naming.Examples.ExamplesRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class ExamplesRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [Obsolete("This property is deprecated, use ColonReplacementFormatAsColonReplacementFormat instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("colonReplacementFormat")]
            public string? ColonReplacementFormat { get; set; }
#nullable restore
#else
            [QueryParameter("colonReplacementFormat")]
            public string ColonReplacementFormat { get; set; }
#endif
            [QueryParameter("colonReplacementFormat")]
            public global::Soenneker.Radarr.OpenApiClient.Models.ColonReplacementFormat? ColonReplacementFormatAsColonReplacementFormat { get; set; }
            [QueryParameter("id")]
            public int? Id { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("movieFolderFormat")]
            public string? MovieFolderFormat { get; set; }
#nullable restore
#else
            [QueryParameter("movieFolderFormat")]
            public string MovieFolderFormat { get; set; }
#endif
            [QueryParameter("renameMovies")]
            public bool? RenameMovies { get; set; }
            [QueryParameter("replaceIllegalCharacters")]
            public bool? ReplaceIllegalCharacters { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("resourceName")]
            public string? ResourceName { get; set; }
#nullable restore
#else
            [QueryParameter("resourceName")]
            public string ResourceName { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("standardMovieFormat")]
            public string? StandardMovieFormat { get; set; }
#nullable restore
#else
            [QueryParameter("standardMovieFormat")]
            public string StandardMovieFormat { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExamplesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Api.V3.Config.Naming.Examples.ExamplesRequestBuilder.ExamplesRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
