// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Radarr.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Lookup.Imdb
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\movie\lookup\imdb
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImdbRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Lookup.Imdb.ImdbRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImdbRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/movie/lookup/imdb{?imdbId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Lookup.Imdb.ImdbRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImdbRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/movie/lookup/imdb{?imdbId*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Models.MovieResource"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Radarr.OpenApiClient.Models.MovieResource?> GetAsync(Action<RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Lookup.Imdb.ImdbRequestBuilder.ImdbRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Radarr.OpenApiClient.Models.MovieResource> GetAsync(Action<RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Lookup.Imdb.ImdbRequestBuilder.ImdbRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Radarr.OpenApiClient.Models.MovieResource>(requestInfo, global::Soenneker.Radarr.OpenApiClient.Models.MovieResource.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Lookup.Imdb.ImdbRequestBuilder.ImdbRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Lookup.Imdb.ImdbRequestBuilder.ImdbRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Lookup.Imdb.ImdbRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Lookup.Imdb.ImdbRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Radarr.OpenApiClient.Api.V3.Movie.Lookup.Imdb.ImdbRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class ImdbRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("imdbId")]
            public string? ImdbId { get; set; }
#nullable restore
#else
            [QueryParameter("imdbId")]
            public string ImdbId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
